[package]
name = "tests_wflow"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
# internal
daybook_core = { workspace = true }
utils_rs = { workspace = true, features = ["hash", "automerge", "console-subscriber"] }
api_utils_rs.workspace = true
wflow.workspace = true

# async
tokio = { workspace = true, features = ["rt", "time", "macros", "sync", "tracing"] }
futures = { workspace = true }

# encoding
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# error
color-eyre = { workspace = true }
thiserror = { workspace = true }

# log
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# sync
samod = { workspace = true, features = ["tokio", "tungstenite"] }
automerge = { workspace = true }


# wasm
wash-runtime.workspace = true
