[package]
name = "wflow_tokio"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["serde"]
serde = []

[lib]
path = "lib.rs"

[dependencies]
# internal
wflow_core.workspace = true
utils_rs.workspace = true
macros.workspace = true

# encoding
serde.workspace = true
serde_json.workspace = true

# async
async-trait.workspace = true
tokio-util.workspace = true
async-channel.workspace = true

# error
anyhow.workspace = true
thiserror.workspace = true
displaydoc.workspace = true
parking_lot.workspace = true

# tokio
tokio.workspace = true

# logging
tracing.workspace = true
