[package]
name = "wflow_sdk"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
api_utils_rs.workspace = true

# serde
serde.workspace = true
serde_json.workspace = true

# errors
color-eyre.workspace = true
thiserror.workspace = true
displaydoc.workspace = true

wit-bindgen.workspace = true

