repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: gh_action/dist/.*.js
      - id: check-ast
      - id: check-json
        exclude: .vscode/.*\.json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
        # exclude all generated files
        exclude: |
          (?x)^(
              Cargo.lock|
              gh_action/.*.js
          )$
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.2
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: local
    hooks:
      # - id: ktlint-fmt
      #   name: format kotlin
      #   language: system
      #   entry: bash -c 'ktlint -F'
      #   pass_filenames: false
      - id: deno-fmt-x
        name: Formt scripts
        language: system
        entry: deno fmt ./x/
        pass_filenames: false
      - id: deno-lint-x
        name: Lint scripts
        language: system
        entry: deno lint ./x/
        pass_filenames: false
      - id: deno-check-x
        name: Check scripts
        language: system
        entry: deno check ./x/
        pass_filenames: false
      # - id: lint-check
      #   name: Ts check
      #   language: system
      #   entry: bash -c 'pnpm -C ./src/daybook_rn/ expo lint'
      #   pass_filenames: false
      #   types:
      #     - ts
      #     - tsx
      #     - javascript
      # - id: tsc-check
      #   name: Ts check
      #   language: system
      #   entry: bash -c 'pnpm -C ./src/daybook_rn/ tsc --noEmit'
      #   pass_filenames: false
      #   types:
      #     - ts
      #     - tsx
      #     - javascript
      # - id: pnpm-install
      #   name: Pnpm install
      #   language: system
      #   entry: bash -c 'pnpm -C ./src/daybook_rn/ install'
      #   pass_filenames: false
      #   files: |
      #     (?x)^(
      #         ./src/daybook_rn/pnpm-lock.yaml|
      #         ./src/daybook_rn/package.json
      #     )$
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
        args:
          - "--locked"
          - "--all-features"
          - "--all-targets"
          - "--"
          - "--deny"
          - "warnings"
