[workspace]
resolver = "3"
members = [
  "./src/agents",
  "./src/btress_api",
  "./src/btress_http",
  # "./src/granary_web",
  # "./src/leptos_oidc",
  "./src/utils_rs",
  "./src/api_utils_rs",
  "./src/xtask",
  "./src/macros",
  "./src/daybook_core",
  "./src/daybook_sync",
  "./src/daybook_api",
  "./src/daybook_http",
  "./src/daybook_types",
  "./src/tests_http",
  # "./src/leptos_wasi/",
]
exclude = [
  "./src/samod"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
# internal
leptos_oidc = { path = "./src/leptos_oidc" }
utils_rs = { path = "./src/utils_rs", default-features = false }
api_utils_rs = { path = "./src/api_utils_rs" }
btress_api = { path = "./src/btress_api" }
macros = { path = "./src/macros" }
daybook_types = { path = "./src/daybook_types", default-features = false }

# futures
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", default-features = false }

# ds
ahash = "0.8"
time = { version = "0.3", default-features = false, features = ["serde"] }
once_cell = "1"
parking_lot = "0.12"
bytes = "1"
url = "2.5.7"

# serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"

leptos = { version = "0.8", default-features = false }
leptos-use = { version = "0.16", default-features = false }
leptos_router = { version = "0.8", default-features = false }

# macros
displaydoc = "0.2"
educe = "0.6"

# errors
thiserror = "2"
anyhow = "1"
garde = { version = "0.22", features = ["derive", "regex", "url", "email"] }
terrors = "0.3.3"

# logging
color-eyre = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "parking_lot",
  "tracing-log"
] }
tracing-unwrap = "1.0"
tracing-appender = "0.2.3"
tracing-error = "0.2.1"

kanidm_client = "1.7.2"
kanidm_proto = "1.7.2"
dotenv-flow = "0.16.2"

# http
axum = { version = "0.8.4", default-features = false }
axum-extra = { version = "0.10.1", default-features = false }
http = "1"
utoipa = { version = "5.4.0", features = ["debug", "uuid", "time", "smallvec",  "preserve_order"] }
# utoipa-swagger-ui = "9"
# http
tower = "0.5"
tower-http = "0.6"

reqwest = { version = "0.12", default-features = false }
gloo = { version = "0.11.0", default-features = false }


# wasm
wit-bindgen = "0.45.1"

automerge = "0.6"
autosurgeon = "0.8.7"
automerge-test = "0.5"
samod = { version = "0.4.0" }
# samod = { path = "src/samod/samod" }

sqlx = { version = "0.8.6", features = [
  "runtime-tokio",
  # "tls-rustls-ring-webpki",
  "time",
  "uuid",
  "macros",
  "json",
  "migrate",
  "ipnetwork",
] }


uniffi = { version = "0.29.4" }