[workspace]
resolver = "3"
members = [
  "./src/api_utils_rs",
  "./src/autosurgeon/autosurgeon",
  "./src/autosurgeon/autosurgeon-derive/",
  "./src/btress_api",
  "./src/btress_http",
  "./src/daybook_api",
  "./src/daybook_core",
  "./src/daybook_ffi",
  "./src/daybook_http",
  # "./src/daybook_restate/",
  "./src/daybook_sync",
  "./src/daybook_wflows/",
  "./src/macros",
  # "./src/sdk-shared-core/",
  "./src/tests_http",
  "./src/tests_wflow",
  "./src/utils_rs",
  "./src/wflow/",
  "./src/wflow_ingress_http/",
  "./src/xtask",
  "./src/wash-plugin-am-repo/",
  # "./src/granary_web",
  # "./src/leptos_oidc",
  # "./src/leptos_wasi/",
]
exclude = [
  "./src/samod"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.91"
authors = []
license = ""
repository = ""

[workspace.dependencies]
# internal
leptos_oidc = { path = "./src/leptos_oidc" }
utils_rs = { path = "./src/utils_rs", default-features = false }
api_utils_rs = { path = "./src/api_utils_rs", default-features = false  }
btress_api = { path = "./src/btress_api" }
macros = { path = "./src/macros" }
daybook_core = { path = "./src/daybook_core", default-features = false }
wflow = { path = "./src/wflow/", default-features = false }
wash-plugin-am-repo = { path = "./src/wash-plugin-am-repo" }

syn = { version = "2", features = ["extra-traits"] }

# futures
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", default-features = false }
tokio-util = { version = "0.7.17", features = [] }

# ds
ahash = "0.8"
time = { version = "0.3", default-features = false, features = ["serde"] }
once_cell = "1"
parking_lot = "0.12"
bytes = "1"
url = "2.5.7"
# scopeguard = "1.2.0"

# encoding
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
multihash = "0.19.3"
data-encoding = "2.9"

# web
leptos = { version = "0.8", default-features = false }
leptos-use = { version = "0.16", default-features = false }
leptos_router = { version = "0.8", default-features = false }

# macros
displaydoc = "0.2"
educe = "0.6"

# errors
thiserror = "2"
anyhow = "1"
garde = { version = "0.22", features = ["derive", "regex", "url", "email"] }
terrors = "0.3.3"

# logging
color-eyre = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "parking_lot",
  "tracing-log"
] }
tracing-unwrap = "1.0"
tracing-appender = "0.2.3"
tracing-error = "0.2.1"
tracing-futures = "0.2.5"

# auth
kanidm_client = "1.7.2"
kanidm_proto = "1.7.2"

# os
dotenv-flow = "0.16.2"

# http
axum = { version = "0.8.6", default-features = false }
axum-extra = { version = "0.10.1", default-features = false }
http = "1"
utoipa = { version = "5.4.0", features = ["debug", "uuid", "time", "smallvec",  "preserve_order"] }
# utoipa-swagger-ui = "9"
# http
tower = "0.5"
tower-http = "0.6"
reqwest = { version = "0.12", default-features = false }
gloo = { version = "0.11.0", default-features = false }


# wasm
wit-bindgen = "0.45.1"

# sync
automerge = "0.7"
# autosurgeon = "0.9"
autosurgeon = { path = "src/autosurgeon/autosurgeon" }
automerge-test = "0.6"
samod = { version = "0.5.0" }
# samod = { path = "src/samod/samod" }
async-channel = "2.5.0"

# db
sqlx = { version = "0.8.6", features = [
  "runtime-tokio",
  # "tls-rustls-ring-webpki",
  "time",
  "uuid",
  "macros",
  "json",
  "migrate",
  "ipnetwork",
] }

# ffi
uniffi = { version = "0.29.4" }
# uniffi = { path = "../uniffi-rs/uniffi/" }

wasmtime = "*"
wash-runtime = "0.1.0"

# [patch.crates-io]
# restate-sdk-shared-core = { path = "./src/sdk-shared-core/" }
