[workspace]
resolver = "2"
members = [
  "./src/btress_api",
  "./src/granary_web",
  "./src/leptos_oidc",
  "./src/utils_rs",
  "./src/xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
leptos_oidc = { path = "./src/leptos_oidc" }
utils_rs = { path = "./src/utils_rs" }

async-trait = "0.1"
futures = "0.3"
tokio = "1"

time = { version = "0.3", default-features = false }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

leptos = { version = "0.7", default-features = false }
leptos-use = { version = "0.15", default-features = false }
leptos_router = { version = "0.7", default-features = false }

reqwest = { version = "0.12", default-features = false }
gloo = { version = "0.11.0", default-features = false }

thiserror = "1.0"

color-eyre = "0.6"
anyhow = "1"

once_cell = "1"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "parking_lot",
  "tracing-log"
] }
tracing-unwrap = "1.0"
