[workspace]
resolver = "2"
members = [
  "./src/granary_web",
  "./src/btress_api",
  "./src/utils_rs"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
utils_rs = { path = "./src/utils_rs" }
async-trait = "0.1"
futures = "0.3"
tokio = "1"
serde_json = "1"
serde = "1"
