await-holding-invalid-types = [
  { path = "dashmap::mapref::one::MappedRef", reason = "potentially deadlocks" },
  { path = "dashmap::mapref::one::MappedRefMut", reason = "potentially deadlocks" },
  { path = "dashmap::mapref::one::Ref", reason = "potentially deadlocks" },
  { path = "dashmap::mapref::one::RefMut", reason = "potentially deadlocks" },
  { path = "dashmap::mapref::entry::Entry", reason = "potentially deadlocks" },
  { path = "dashmap::mapref::multiple::RefMulti", reason = "potentially deadlocks" },
  { path = "dashmap::mapref::multiple::RefMutMulti", reason = "potentially deadlocks" },
  { path = "tokio::sync::Mutex", reason = "potential futurelock" }
]
disallowed-names = [
  "a","b","c","d","e",
  "f","g","h","i","j",
  "k","l","m","n","o",
  "p","q","r","s","t",
  "u","v","w","x","y",
  "z", ".."
]
