name = "btress_http"
version = "0.1.0"
language = "rust"
type = "component"
path = "./../../"
build = "./../../target/wash"

[component]
wit_world = "server"
wasm_target = "wasm32-wasip2"
build_command = "deno run -A ./x/build-btress-http.ts"
build_artifact = "./target/wasm32-wasip2/debug/btress_http_plugged.wasm"

# [rust]
# target_path = "./../../target"
# debug = true
