[package]
name = "utils_rs"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
path = "lib.rs"

[features]
default = ["hash", "native", "downloader"]
downloader = ["dep:reqwest", "tokio/fs", "tokio/io-util"]
hash = [
    "dep:data-encoding",
    "dep:bs58",
    "dep:multihash",
    "dep:json-canon",
    "dep:sha2",
    "tokio/io-util",
    "dep:blake3",
]
native = [
    "uuid/rng-rand",
    # "dep:ahash",
]
browser = ["uuid/js"]

[dependencies]
# futures
async-trait.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["sync", "macros", "rt", "rt-multi-thread", "time"] }
reqwest = { workspace = true, default-features = false, features = ["stream", "rustls-tls"], optional = true }

# encoding
serde.workspace = true
serde_json.workspace = true
multihash = { workspace = true, optional = true }
data-encoding = { workspace = true, optional = true }
bs58 = { workspace = true, optional = true }
sha2 = { version = "=0.11.0-rc.2", optional = true }
json-canon = { version = "0.1.3", optional = true }
blake3 = { workspace = true, optional = true }

# ds
# ahash = { workspace = true, optional = true }
dashmap = { version = "6.1", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
indexmap = "2.11"
regex = "1"
time.workspace = true
url.workspace = true
jiff = { version = "0.2.17", features = ["serde"] }

# errors
thiserror.workspace = true
anyhow.workspace = true

# macros
displaydoc.workspace = true
educe.workspace = true

# utoipa-swagger-ui = "9"

dotenv-flow.workspace = true

# logging
tracing.workspace = true
tracing-subscriber = { workspace = true }
tracing-unwrap.workspace = true
tracing-appender.workspace = true
tracing-error.workspace = true
tracing-futures.workspace = true
color-eyre.workspace = true


[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
console-subscriber = { version = "0.5.0" }
