[package]
name = "utils_rs"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[features]
automerge = ["dep:autosurgeon", "dep:automerge", "dep:samod", "dep:tokio-tungstenite"]
default = ["automerge"]

[dependencies]
# futures
async-trait.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "macros"] }

# serde
serde.workspace = true
serde_json.workspace = true

# ds
ahash.workspace = true
dashmap = "6.1"
uuid = { version = "1", features = ["v7", "serde"] }
indexmap = "2.11"
regex = "1"
time.workspace = true

# errors
thiserror.workspace = true

# macros
displaydoc.workspace = true
educe.workspace = true

# utoipa-swagger-ui = "9"

dotenv-flow.workspace = true

# logging
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true
tracing-appender.workspace = true
tracing-error.workspace = true
tracing-futures.workspace = true
color-eyre.workspace = true

automerge = { workspace = true, optional = true }
autosurgeon = { workspace = true, optional = true }
samod = { workspace = true, optional = true }
tokio-tungstenite = { version = "0.27.0", features = ["url"], optional = true }

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2"
