[package]
name = "utils_rs"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
# futures
async-trait.workspace = true
futures.workspace = true
tokio.workspace = true

# serde
serde.workspace = true
serde_json.workspace = true

# ds
ahash = "0.8"
dashmap = "6.1"
uuid = "1"
indexmap = "2.7"
regex = "1"

# errors
thiserror.workspace = true
garde.workspace = true

# macros
displaydoc.workspace = true
educe.workspace = true

axum = { version = "0.8.1" }
axum-extra = { version = "0.10.0", features = ["typed-header"] }

utoipa = { version = "5.3.1", features = ["debug", "uuid", "time", "smallvec", "axum_extras", "preserve_order"] }
utoipa-swagger-ui = "9"

# http
tower = "0.5"
tower-http = "0.6"
hyper = "1"

dotenv-flow.workspace = true

# logging
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true
tracing-appender.workspace = true
tracing-error.workspace = true
color-eyre.workspace = true
