[package]
name = "utils_rs"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[features]
default = ["automerge-repo", "hash", "native"]
automerge = ["dep:autosurgeon", "dep:automerge"]
automerge-repo = ["automerge", "dep:samod", "dep:tokio-tungstenite"]
hash = ["dep:multihash", "dep:json-canon", "dep:sha2", "dep:data-encoding", "tokio/io-util", "dep:blake3"]
console-subscriber = ["dep:console-subscriber"]
native = [
    "uuid/rng-rand",
    # "dep:ahash",
]
browser = [
    "uuid/js",
]

[dependencies]
# futures
async-trait.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["sync", "macros", "rt", "time"] }

# encoding
serde.workspace = true
serde_json.workspace = true
multihash = { workspace = true, optional = true }
data-encoding = { workspace = true, optional = true }
sha2 = { version = "=0.11.0-pre.5", optional = true }
json-canon = { version = "0.1.3", optional = true }
blake3 = { workspace = true, optional = true }

# ds
# ahash = { workspace = true, optional = true }
dashmap = { version = "6.1", features = ["serde"] }
uuid = { version = "1", features = ["serde"] }
indexmap = "2.11"
regex = "1"
time.workspace = true

# errors
thiserror.workspace = true
anyhow.workspace = true

# macros
displaydoc.workspace = true
educe.workspace = true

# utoipa-swagger-ui = "9"

dotenv-flow.workspace = true

# logging
tracing.workspace = true
tracing-subscriber = { workspace = true }
tracing-unwrap.workspace = true
tracing-appender.workspace = true
tracing-error.workspace = true
tracing-futures.workspace = true
color-eyre.workspace = true

automerge = { workspace = true, optional = true }
autosurgeon = { workspace = true, optional = true }
samod = { workspace = true, optional = true }
tokio-tungstenite = { version = "0.27.0", features = ["url"], optional = true }
console-subscriber = { version = "0.5.0", optional = true }
jiff = "0.2.17"

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2"
