[package]
name = "utils_rs"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
# futures
async-trait.workspace = true
futures.workspace = true
tokio.workspace = true

# serde
serde.workspace = true
serde_json.workspace = true

# ds
ahash.workspace = true
dashmap = "6.1"
uuid = { version = "1", features = ["v7", "serde"] }
indexmap = "2.7"
regex = "1"
time.workspace = true

# errors
thiserror.workspace = true

# macros
displaydoc.workspace = true
educe.workspace = true

# utoipa-swagger-ui = "9"

dotenv-flow.workspace = true

# logging
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true
tracing-appender.workspace = true
tracing-error.workspace = true
color-eyre.workspace = true
