[package]
name = "wash_plugin_utils"
version.workspace = true
edition.workspace = true

[features]
default = []

[lib]
path = "lib.rs"

[dependencies]
# internal
utils_rs.workspace = true
macros.workspace = true

# encoding
serde.workspace = true
serde_json.workspace = true

# async
futures.workspace = true
async-trait.workspace = true
tokio-util.workspace = true
async-channel.workspace = true

# error
anyhow.workspace = true
thiserror.workspace = true
displaydoc.workspace = true
parking_lot.workspace = true

# wasm
wasmtime.workspace = true
wash-runtime.workspace = true

tracing.workspace = true
ollama-rs = "0.3.3"
url.workspace = true



