[package]
name = "wash_plugin_am_repo"
version.workspace = true
edition.workspace = true

[features]
default = []
uniffi = []

[lib]
path = "lib.rs"
# crate-type = ["cdylib"]

[dependencies]
# internal
utils_rs = { workspace = true, features = ["automerge", "hash"] }
macros.workspace = true

# encoding
serde.workspace = true
serde_json.workspace = true
data-encoding.workspace = true

# async
async-trait.workspace = true
tokio-util.workspace = true
async-channel.workspace = true

# error
anyhow.workspace = true
thiserror.workspace = true
displaydoc.workspace = true
parking_lot.workspace = true

# wasm
# wasmcloud-component = "0.2.0"
# wit-bindgen.workspace = true
wasmtime.workspace = true
wash-runtime.workspace = true

# sync
autosurgeon = { workspace = true, features = ["uuid"] }
automerge = { workspace = true }
samod = { workspace = true, features = ["tokio", "tungstenite"] }

tracing.workspace = true

