[alias]
x = "run --package xtask --"

[build]
rustflags = ["--cfg", "tokio_unstable"]

[profile.dev]
# One debuginfo file per dependency, to reduce file size of tests/examples.
# Note that this value is not supported on Windows.
# See https://doc.rust-lang.org/cargo/reference/profiles.html#split-debuginfo
split-debuginfo="unpacked"
