[package]
name = "tests_http"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
reqwest = { workspace = true, features = ["json", "gzip", "deflate", "brotli", "charset"], default-features = false }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt", "time", "macros"] }

utils_rs.workspace = true
wadm-client = "0.10.0"
wadm-types = "0.8.3"
futures = { workspace = true }

sqlx = { workspace = true, features = ["postgres"] }
rand = "0.9.2"
url = "2.5"
