[package]
name = "daybook_core"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]
name = "daybook_core"
path = "lib.rs"

[dependencies]
utils_rs.workspace = true

tracing-unwrap.workspace = true

serde.workspace = true
serde_json.workspace = true

color-eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
once_cell.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "fs"] }
time.workspace = true
rust_decimal = "1.37.1"

uniffi = { version = "0.29.3", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.29.3", features = [ "build" ] }
