[package]
name = "daybook_core"
version.workspace = true
edition.workspace = true

[[bin]]
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[lib]
crate-type = ["cdylib"]
name = "daybook_core"
path = "lib.rs"

[dependencies]
# internal
utils_rs.workspace = true

# serde
serde.workspace = true
serde_json.workspace = true

# error
color-eyre.workspace = true
thiserror.workspace = true

# log
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true

# ds
once_cell.workspace = true
time.workspace = true
rust_decimal = "1.37.1"

# async
tokio = { workspace = true, features = ["rt-multi-thread","sync", "macros", "fs"] }

# ffi
uniffi = { version = "0.29.4", features = ["cli"] }

# sync
autosurgeon = { workspace = true, features = ["uuid"] }
automerge = { workspace = true }

[build-dependencies]
uniffi = { version = "0.29.4", features = [ "build" ] }
