[package]
name = "daybook_core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
name = "daybook_core"
path = "lib.rs"

[features]
default = ["uniffi"]
uniffi = ["dep:uniffi"]

[dependencies]
# internal
utils_rs = { workspace = true, features = ["hash", "native", "automerge-repo"] }
api_utils_rs = { workspace = true, features = ["automerge"] }
wflow = { workspace = true }
daybook_types = { workspace = true, features = [
    "automerge",
    "uniffi",
    "wit",
    "schemars",
] }
wash_plugin_wflow.workspace = true
wash_plugin_utils.workspace = true
wash_plugin_mltools.workspace = true

# encoding
serde.workspace = true
serde_json.workspace = true

# error
color-eyre.workspace = true
thiserror.workspace = true
displaydoc.workspace = true
anyhow = { workspace = true }

# log
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true

# ds
once_cell.workspace = true
time.workspace = true
url.workspace = true
garde.workspace = true
struct-patch.workspace = true
data-encoding.workspace = true
bs58.workspace = true
semver = "1"
addr.workspace = true

# async
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "sync",
    "macros",
    "fs",
] }
tokio-util.workspace = true
futures = { workspace = true }
async-trait.workspace = true

# ffi
uniffi = { workspace = true, features = ["cli"] }

# sync
autosurgeon = { workspace = true, features = ["uuid"] }
automerge = { workspace = true }
samod = { workspace = true, features = ["tokio", "tungstenite"] }

# http
reqwest.workspace = true

# db
sqlx = { workspace = true, features = ["sqlite"] }
sqlite-vec = "0.1.6"

# misc
pastey.workspace = true
directories.workspace = true

# wasm
wash-runtime = { workspace = true }
wasmtime = { workspace = true }

schemars = { version = "1.2", features = [
    "uuid1",
    "semver1",
    "url2",
    "jiff02",
    "indexmap2",
] }
mltools.workspace = true

[build-dependencies]
uniffi = { workspace = true, features = ["build"], optional = true }

[dev-dependencies]
tokio-stream = "0.1.17"
tokio-util = { workspace = true }
wflow = { workspace = true, features = ["test-harness"] }
insta = { workspace = true, features = ["json"] }
wash_plugin_am_repo.workspace = true
tempfile = "3.14.0"
