[package]
name = "daybook_core"
version.workspace = true
edition.workspace = true

[lib]
name = "daybook_core"
path = "lib.rs"

[features]
default = ["uniffi"]
uniffi = ["dep:uniffi"]

[dependencies]
# internal
utils_rs = { workspace = true, features = ["hash"] }
api_utils_rs = { workspace = true, features = ["automerge"] }
wflow = { workspace = true }

# encoding
serde.workspace = true
serde_json.workspace = true

# error
color-eyre.workspace = true
thiserror.workspace = true
displaydoc.workspace = true

# log
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true

# ds
once_cell.workspace = true
time.workspace = true
rust_decimal = "1.37.2"
parking_lot.workspace = true
url.workspace = true
garde.workspace = true
struct-patch = "0.10.4"

# async
tokio = { workspace = true, features = ["rt-multi-thread","sync", "macros", "fs"] }
tokio-util.workspace = true
futures = { workspace = true }
async-trait.workspace = true

# ffi
uniffi = { workspace = true, features = ["cli"] }

# sync
autosurgeon = { workspace = true, features = ["uuid"] }
automerge = { workspace = true }
samod = { workspace = true, features = ["tokio", "tungstenite"] }

# http
reqwest.workspace = true

# misc
sqlx = { workspace = true, features = ["sqlite"] }
pastey = "0.1"
directories = "6.0.0"

[build-dependencies]
uniffi = { workspace = true, features = [ "build" ], optional = true }

[dev-dependencies]
tokio-stream = "0.1.17"
tokio-util = { workspace = true, features = [] }
insta = { workspace = true, features = ["json"] }
wflow = { workspace = true, features = ["test-harness"] }
utils_rs = { workspace = true, features = []}

