[package]
name = "daybook_core"
version.workspace = true
edition.workspace = true

[lib]
name = "daybook_core"
path = "lib.rs"

[features]
default = ["uniffi"]
uniffi = ["dep:uniffi"]

[dependencies]
# internal
utils_rs = { workspace = true, features = ["hash"] }

# serde
serde.workspace = true
serde_json.workspace = true
api_utils_rs.workspace = true

# error
color-eyre.workspace = true
thiserror.workspace = true
displaydoc.workspace = true

# log
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true

# ds
once_cell.workspace = true
time.workspace = true
rust_decimal = "1.37.2"
parking_lot.workspace = true
url.workspace = true
garde.workspace = true


# async
tokio = { workspace = true, features = ["rt-multi-thread","sync", "macros", "fs"] }
futures = { workspace = true }

# ffi
uniffi = { workspace = true, features = ["cli"] }

# sync
autosurgeon = { workspace = true, features = ["uuid"] }
automerge = { workspace = true }
samod = { workspace = true, features = ["tokio", "tungstenite"] }

# http
reqwest.workspace = true

sqlx = { workspace = true, features = ["sqlite"] }

pastey = "0.1"
struct-patch = "0.10.4"
directories = "6.0.0"
async-trait.workspace = true

# wasm
wash-runtime.workspace = true

[build-dependencies]
uniffi = { workspace = true, features = [ "build" ], optional = true }

[dev-dependencies]
tokio-stream = "0.1.17"
tokio-util = { workspace = true, features = [] }

