[package]
name = "daybook_core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
name = "daybook_core"
path = "lib.rs"

[features]
default = ["uniffi"]
uniffi = ["dep:uniffi"]

[dependencies]
#
# internal
am_utils_rs = { workspace = true, features = ["repo", "iroh"] }
api_utils_rs = { workspace = true, features = ["automerge"] }
daybook_types = { workspace = true, features = [
    "automerge",
    "uniffi",
    "wit",
    "schemars",
] }
mltools = { workspace = true, features = ["hf_hub", "tests"] }
utils_rs = { workspace = true, features = ["hash", "native", "downloader"] }
wash_plugin_mltools.workspace = true
wash_plugin_utils.workspace = true
wash_plugin_wflow.workspace = true
wflow = { workspace = true }

#
# encoding
serde.workspace = true
serde_json.workspace = true
zstd.workspace = true

#
# error
anyhow.workspace = true
color-eyre.workspace = true
displaydoc.workspace = true
thiserror.workspace = true

#
# log
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true

#
# ds
once_cell.workspace = true
time.workspace = true
url.workspace = true
garde.workspace = true
struct-patch.workspace = true
data-encoding.workspace = true
bs58.workspace = true
semver = "1"
addr.workspace = true

#
# async
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "sync",
    "macros",
    "fs",
] }
tokio-util.workspace = true
futures = { workspace = true }
async-trait.workspace = true

#
# ffi
uniffi = { workspace = true, features = ["cli"] }

#
# sync
autosurgeon = { workspace = true, features = ["uuid"] }
automerge = { workspace = true }
samod = { workspace = true, features = ["tokio", "tungstenite"] }

#
# http
reqwest.workspace = true

#
# db
sqlx = { workspace = true, features = ["sqlite"] }
sqlite-vec.workspace = true
libsqlite3-sys = "0.30.1"

#
# misc
pastey.workspace = true
directories.workspace = true
fs4.workspace = true
image = { version = "0.25", default-features = true, features = ["jpeg", "png", "gif", "webp", "bmp"] }

#
# wasm
wash-runtime = { workspace = true }
wasmtime = { workspace = true }

#
# schema
schemars = { version = "1.2", features = [
    "uuid1",
    "semver1",
    "url2",
    "jiff02",
    "indexmap2",
] }
jsonschema = { version = "0.42.0", default-features = false }

#
# sync
iroh = { workspace = true }
iroh-tickets = "0.3.0"

#
# os
rand.workspace = true
keyring = "3.6.3"
iroh-blobs = "0.98.0"
iroh-docs = "0.96.0"
iroh-gossip = "0.96.0"

[build-dependencies]
uniffi = { workspace = true, features = ["build"], optional = true }
zstd.workspace = true
# wasmtime.workspace = true

[dev-dependencies]
tokio-stream = "0.1.17"
tokio-util = { workspace = true }
wflow = { workspace = true, features = ["test-harness"] }
insta = { workspace = true, features = ["json"] }
tempfile.workspace = true
loom.workspace = true
