[bindings.kotlin]
package_name = "org.example.daybook.uniffi.core"

[bindings.kotlin.custom_types.OffsetDateTime]
# Name of the type in the Kotlin code
type_name = "Instant"
# Classes that need to be imported
imports = [ "kotlin.time.Instant" ]
# Expression to convert the builtin type the custom type.  In this example, `{}` will be replaced with the int value.
lift = "Instant.fromEpochSeconds({}, 0)"
# Expression to convert the custom type to the builtin type.  In this example, `{}` will be replaced with the URL value.
lower = "{}.epochSeconds"

[bindings.kotlin.custom_types.Uuid]
type_name = "Uuid"
imports = [ "kotlin.uuid.Uuid" ]
lift = "Uuid.fromByteArray({})"
lower = "{}.toByteArray()"

# [bindings.kotlin.custom_types.ChangeHashSet]
# type_name = "List<Str"
# imports = [ ]
# lift = "Uuid.fromByteArray({})"
# lower = "{}.toByteArray()"
