[package]
name = "wflow_core"
version.workspace = true
edition.workspace = true

[features]
default = ["serde"]
serde = []
test-harness = []

[lib]
path = "lib.rs"

[dependencies]
# internal
utils_rs.workspace = true
macros.workspace = true

# encoding
serde.workspace = true
serde_json.workspace = true

# async
futures.workspace = true
async-trait.workspace = true

# error
anyhow.workspace = true
thiserror.workspace = true
displaydoc.workspace = true
parking_lot.workspace = true

[dev-dependencies]
loom = "0.7.2"

