[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "xtask"
path = "main.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
# zitadel = { version = "5.5.1", features = ["api"] }
# ahash.workspace = true

# kanidm_client.workspace = true
# kanidm_proto.workspace = true

dotenv-flow.workspace = true

utils_rs = { workspace = true, features = ["native"] }

tokio = { workspace = true, features = ["rt-multi-thread", "fs", "time"] }
http.workspace = true

# generator
heck = "0.5.0"
bon = "3.7.2"
indenter = "0.3.4"

data-encoding.workspace = true
ollama-rs = { version = "0.3.3", default-features = false, features = ["rustls"] }

