[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "xtask"
path = "main.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
# zitadel = { version = "5.5.1", features = ["api"] }
# ahash.workspace = true

# kanidm_client.workspace = true
# kanidm_proto.workspace = true

dotenv-flow.workspace = true

utils_rs = { workspace = true, features = ["native"] }
mltools = { workspace = true, default-features = true, features = ["tests"] }

tokio = { workspace = true, features = ["rt-multi-thread", "fs", "time"] }
http.workspace = true
sqlx = { workspace = true, features = ["sqlite"] }
sqlite-vec.workspace = true
libsqlite3-sys = "0.30.1"
fastembed = { version = "5.8.1", default-features = false, features = ["ort-download-binaries", "image-models", "hf-hub-rustls-tls"] }

# generator
heck = "0.5.0"
bon.workspace = true
indenter = "0.3.4"

data-encoding.workspace = true
ollama-rs = { version = "0.3.4", default-features = false, features = ["rustls"] }
