[package]
name = "api_utils_rs"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
utils_rs.workspace = true

# futures
async-trait.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "sync", "time", "io-util"] }

# serde
serde.workspace = true
serde_json.workspace = true

axum = { version = "0.8.4", default-features = false, features = [
  "form", "json", "macros", "multipart", "query", "original-uri",
  "query", "tower-log", "tracing"
  ] }
axum-extra = { version = "0.10.0", features = ["typed-header"] }

utoipa = { version = "5.3.1", features = ["debug", "uuid", "time", "smallvec", "axum_extras", "preserve_order"] }
# utoipa-swagger-ui = "9"
# http
tower = "0.5"
tower-http = "0.6"



# errors
color-eyre.workspace = true
garde.workspace = true
thiserror.workspace = true
displaydoc.workspace = true

wit-bindgen.workspace = true

# http
# hyper = "1"
# http.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# db
sqlx.workspace = true
