name: townframe
services:
  #
  # db services
  postgres:
    profiles: [db, auth]
    build:
      context: .
      dockerfile: ./postgres.Containerfile
    # image: docker.io/library/postgres:17
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    #   start_period: 20s
    #   interval: 30s
    #   retries: 5
    #   timeout: 5s
    networks: [net-one]
    env_file: [.env]
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD?"PGPASSWORD not set."}
      POSTGRES_USER: ${PGUSER?"PGUSER not set."}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql:Z


  redis:
    profiles: [db]
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks: [net-one]
    env_file: [.env]
    volumes:
      - redisdata:/data

  #
  # auth services
  spicedb:
    image: ghcr.io/authzed/spicedb:v1.40.0
    ports:
      - 50051:50051
    depends_on: [postgres]
    profiles: [auth]
    networks: [net-one]
    env_file: [.env]

  zitadel:
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    restart: unless-stopped
    depends_on: [postgres]
    profiles: [disabled]
    networks: [net-one]
    env_file: [.env]
    ports:
      - '${ZITADEL_EXTERNALPORT?"ZITADEL_EXTERNALPORT not set"}:8080'

  kanidmd:
    image: 'docker.io/kanidm/server:1.5.0'
    command: >
      sh -c "/sbin/kanidmd cert-generate &&
             /sbin/kanidmd server -c /data/server.toml"
    restart: unless-stopped
    profiles: [auth]
    networks: [net-one]
    env_file: [.env]
    ports:
      - '8443:8443'
      - '3636:3636'
    # podman mounts volumes as root otherwise
    # userns_mode: keep-id:uid=1000,gid=1000
    # security_opt:
    #   - label=disable
    volumes:
      - kanidmdata:/data
      - ./kanidm.toml:/data/server.toml:ro,Z
      - ./kandidm_certs:/certs:Z

  #
  # cli tools
  zed:
    image: ghcr.io/authzed/zed:v0.27.0
    profiles: [cli]
    networks: [net-one]
    env_file: [.env]
    # network_mode: host

  flyway:
    image: docker.io/flyway/flyway:11.4.0-alpine
    profiles: [cli]
    networks: [net-one]
    env_file: [.env]
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${DB_NAME}?user=${PGUSER}&password=${PGPASSWORD}
    # network_mode: host
    volumes:
      - ..:/flyway/conf:ro,Z
      - ${MIG_DIR:-./migrations/}:/migrations:ro,Z

  postgrest-btress:
    image: docker.io/postgrest/postgrest:v12.2.8
    profiles: [db]
    networks: [net-one]
    env_file: [.env]
    environment:
      PGDATABASE: btress
    ports:
      - 54320:3000
    depends_on:
      - postgres

  electric-btress:
    image: docker.io/electricsql/electric:1.0.0-beta.19
    profiles: [disabled]
    networks: [net-one]
    env_file: [.env]
    environment:
      DATABASE_URL: postgresql://${PGUSER}:${PGPASSWORD}@postgres:5432/btress?sslmode=disable
    ports:
      - 54330:3000
    depends_on:
      - postgres

volumes:
  pgdata:
  redisdata:
  kanidmdata:

networks:
  net-one:

# x-podman:
#   in_pod: false
