name = "http-hello-world"
version = "0.1.0"
language = "rust"
type = "component"
path = "./../../"
build = "./target/wash"

[component]
wit_world = "hello"
wasm_target = "wasm32-wasip2"
build_command = "cargo b -p http-hello-world --target wasm32-wasip2"
build_artifact = "./target/wasm32-wasip2/debug/http_hello_world.wasm"

# [rust]
# target_path = "./../../target"
# debug = true
